import Head from 'next/head'
import Navigation from '../components/Navigation'
export default function Home() {
  return (
    <>
      <Head>
        <title>Ronell Roxas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation/>
    </>
  )
}
